### ISSUE TITLE
Unable to connect to private K8s from my azure devops self hosted agents

### ISSUE THREAD

**Issue by surya2155** [preddy727/aksprivatecluster#2]
I tried to link my self hosted agent Vnet to the private azure DNS (using the vnet linking ) which already has 'A' rule for the private K8s api endpoint address. and when trying to do kubectl get all from that agent, it is showing timeout issues. (I have already executed az aks get-credentials -n name -g rg).

can anyone has any idea, how to connect to private K8s from self hosted agent.(not by vnet peering or creating the self hosted agent in the K8s vnet).

**Comment by preddy727** [comment]
Create the private endpoint in the same vnet as your self hosted agent as described on the GitHub page. A separate private dns zone needs to be created in the bastion subnet. The self hosted agent needs to be in the bastion subnet.
